#!/usr/bin/env python3

import argparse, os

class color:
    blue = "\033[1;34;48m"
    red = "\033[1;31;48m"
    end = "\033[1;37;0m"

if os.geteuid() != 0:
    exit(color.red + " You need to have root privileges to run this script!")

# ARGPARSE ARGUMENTS
parser = argparse.ArgumentParser(description="Change the backlight brightness")
parser.add_argument("backlight", nargs="?", type=int, default=255, help="Set the backlight brightness (default: 255)")
parser.add_argument("--get", action="store_true", help="Get the backlight brightness")
args = parser.parse_args()

# CONSTANTS
BACKLIGHT_PATH = "/sys/class/backlight"

def find_device_path():
    try:
        device_path = next(os.walk(BACKLIGHT_PATH))[1]

        if not device_path:
            raise FileNotFoundError("no device directories found in: " + BACKLIGHT_PATH)
        
        backlight_device_path = os.path.join(BACKLIGHT_PATH, device_path[0])
        return backlight_device_path

    except (StopIteration, FileNotFoundError) as e:
        print(f" {color.red}Error finding device directory:{color.end} {e}")
        exit(1)

def get_actual_brightness(actual_brightness_path):
    try:
        with open(actual_brightness_path, "r") as actual_brightness_file:
            return actual_brightness_file.read().strip()

    except IOError as e:
        print(f" {color.red}Error reading from {actual_brightness_file_path}:{color.end} {e}")
        exit(1)

def main():
    backlight_device_path = find_device_path()
    actual_brightness_path = os.path.join(backlight_device_path, "actual_brightness")
    brightness_path = os.path.join(backlight_device_path, "brightness")
    max_brightness_path = os.path.join(backlight_device_path, "max_brightness")

    if args.get:
        actual_brightness = get_actual_brightness(actual_brightness_path)
        print(f" {color.blue}Backlight brightness:{color.end} {actual_brightness}")
    else:
        try:
            with open(brightness_path, "w") as brightness_file:
                brightness_file.write(str(args.backlight))
        except IOError as e:
            print(f" {color.red}Error writing to {brightness_path}:{color.end} {e}")

if __name__ == "__main__":
    main()

