#!/usr/bin/env python3

import argparse, os

class color:
    blue = "\033[1;34;48m"
    red = "\033[1;31;48m"
    end = "\033[1;37;0m"

if os.geteuid() != 0:
    exit(color.red + " You need to have root privileges to run this script!")

# ARGPARSE ARGUMENTS
parser = argparse.ArgumentParser(description="Change the backlight brightness")
parser.add_argument("backlight", nargs="?", type=int, default=255, help="Set the backlight brightness (default: 255)")
parser.add_argument("--get", action="store_true", help="Get the backlight brightness")
args = parser.parse_args()

# CONSTANTS
BACKLIGHT_PATH = "/sys/class/backlight"

def find_device_path():
    try:
        device_path = next(os.walk(backlight_path))[1]

        if not device_path:
            raise FileNotFoundError("no device directories found in: " + backlight_path)

        return device_path[0]

    except (StopIteration, FileNotFoundError) as e:
        print(f" {color.red}Error finding device directory:{color.end} {e}")
        exit(1)

def get_brightness(brightness_file_path):
    try:
        with open(brightness_file_path, "r") as brightness_file:
            return brightness_file.read().strip()

    except IOError as e:
        print(f" {color.red}Error reading from {brightness_file_path}:{color.end} {e}")
        exit(1)

def main():
    device_path = find_device_path()
    brightness_file_path = os.path.join(backlight_path, device_path, "brightness")

    if args.get:
        current_brightness = get_brightness(brightness_file_path)
        print(f" {color.blue}Backlight brightness:{color.end} {current_brightness}")
    else:
        try:
            with open(brightness_file_path, "w") as brightness_file:
                brightness_file.write(str(args.backlight))
        except IOError as e:
            print(f" {color.red}Error writing to {brightness_file_path}:{color.end} {e}")

if __name__ == "__main__":
    main()

