#!/usr/bin/env python3

import time

class color:
    blue = "\033[1;34;48m"
    end = "\033[1;37;0m"

try:
    def print_time(local_time):
        print("\033[K", end="") # Clear the line
        print("    " + color.blue + "Local time:" + color.end, local_time, end="\r", flush=True) # Print the time with formatting, color, line overwriting and no buffering
        time.sleep(0.1)
    
    while True:
        local_time = time.strftime("%A %Y-%m-%d %H:%M:%S", time.localtime())
        print_time(local_time)

except KeyboardInterrupt:
    print("") # Use print instead of pass to keep the time on the terminal after exiting
